# Generated by Django 5.0.1 on 2024-01-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lasT_name',
            new_name='last_name',
        ),
    ]
